# Generated by Django 3.1.6 on 2021-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='titre',
            new_name='title',
        ),
    ]
